spring:
  application:
    name: transaction_service
  datasource:
    username: secret
    password: secret
    url: jdbc:postgresql://localhost:5432/user_service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: false
    hibernate:
      ddl-auto: update

server:
  port: 0

kafka:
  host: localhost:9092
  topics:
    user-created:
      topic: user_service.user_created.0
      consumerGroup: ${spring.application.name}-user-created-consumer
      replicationFactor: 1
      retentionInMs: 604800000
    transaction-created:
      topic-name: ${spring.application.name}.transaction_created.0
      partition-count: 1
      replication-factor: 1
      retention-in-ms: 604800000